### ISSUE TITLE
Requires password given on command line, which is a security risk

### ISSUE THREAD

**Issue by ncabatoff** [brandonweeks/vmware_exporter#1]
I don't want my password to be visible in /proc.  Suggested alternatives: (1) allow prompting for password to read from stdin, (2) allow reading password from a file.

**Comment by brandonweeks** [comment]
I was planning on reading from environment variables instead of argv as I personally deploy with Docker. Thoughts?

**Comment by ncabatoff** [comment]
It's definitely better than on the command line, but I believe it's less secure than the other options I gave.  Here's one of many online references describing the pitfalls: http://movingfast.io/articles/environment-variables-considered-harmful/
There's a HN discussion about it (https://news.ycombinator.com/item?id=8826024) which discusses some of the tradeoffs.

All the options being floated are pretty cheap to implement, no harm in pushing the decision to the user so long as you don't mind the extra code to maintain. The package https://github.com/bgentry/speakeasy can apparently be used to read passwords from stdin without echoing, though I haven't tried it myself.  I wouldn't mind creating PRs for that and the file-based solution if you like.

**Comment by brandonweeks** [comment]
In general I agree with the issues around storing secrets in environment variables, however using Docker with something like [Kubernetes Secrets](http://kubernetes.io/docs/user-guide/secrets/) I believe to be rather secure.

How about the default config reading the environment variables and then loading the config file to override them?

**Comment by ncabatoff** [comment]
Works for me.
